[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type=["rlib","cdylib"]
name = "core"

[dependencies]
ordermap = "0.3.5"
rustler = "0.22.2"