name: BigData
on: [push]

env:
   CARGO_TERM_COLOR: always

jobs:
  BigData-test:
    runs-on: ubuntu-latest
    container:
      image: erlang:22.3.4.1
    steps:
    - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - run: rustup component add clippy
    - uses: actions/checkout@v2
    - name: Clippy
      run: sh crates/build_crates.sh clippy
    - name: Test
      run: make test